spring.application.name=owner-service
server.port=8081

spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_OWNER_DB}
spring.datasource.username=${POSTGRES_OWNER_USER}
spring.datasource.password=${POSTGRES_OWNER_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
